### ISSUE TITLE
Bad strip detection not using aliases

### ISSUE THREAD

**Issue by espencer78** [Chilldose/COMET#21]
When I tried adding the bad_strip_detection to my analyses I got an error that it couldn't find the key "Istrip" in the variable working_data (line 546 of bad_strip_detection.py).  When I looked at what was in working_data I saw it was all the column names from my text files, but the aliases I had put into my config file did not cause my column name to be properly aliased to "Istrip" in the bad_strip_detection.py script.

**Comment by Chilldose** [comment]
You are right, this is a bug!

I will fix it in the next update.

**Comment by Chilldose** [comment]
The bug should be fixed now.
